{% set name = "bruco" %}
{% set version = "0.1.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c6b22e51b8ae9076f06838a38f119fd362babf680ecf720f54bdfb20aae0446f

build:
  number: 0
  skip: true  # [win]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - gwdatafind
    - gwpy
    - matplotlib-base
    - numpy
    - python
    - scipy

test:
  requires:
    - pip
  imports:
    - bruco
  commands:
    - python -m bruco --help
    - bruco --help
    - pip check

about:
  home: https://git.ligo.org/gabriele-vajente/bruco
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Brute force coherence

extra:
  recipe-maintainers:
    - duncanmmacleod
