{% set name = "bruco" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9948d16e0ad39e8501eb7d00e615d27e185bc0ef42869dedb6a5ed0e52738cc8

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    # extras for cross-compilation
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - python                              # [build_platform != target_platform]
  host:
    - pip
    - python
    - setuptools
  run:
    - gpstime
    - gwdatafind
    - gwpy
    - matplotlib-base
    - numpy
    - python
    - scipy

test:
  requires:
    - pip
  imports:
    - bruco
  commands:
    # check requirements
    - python -m pip check
    # check command-line interface
    - python -m bruco --help
    - bruco --help  # [unix]

about:
  home: https://git.ligo.org/gabriele-vajente/bruco
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Brute force coherence

extra:
  recipe-maintainers:
    - duncanmmacleod
