{% set name = "bruco" %}
{% set version = "0.1.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 999761de5c7ed8dee17efc91ef2d463a7f3407bef95e5b117b7f3fb76473d7c0

build:
  number: 1
  skip: true  # [win]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - gwdatafind
    - gwpy
    - matplotlib-base
    - numpy
    - python
    - scipy

test:
  imports:
    - bruco
  commands:
    - python -m bruco --help
    - bruco --help

about:
  home: https://git.ligo.org/gabriele-vajente/bruco
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Brute force coherence

extra:
  recipe-maintainers:
    - duncanmmacleod
