travis:
  secure:
    BINSTAR_TOKEN: jVV4KaJP106yX1buQITQVrJL1zEJfn6t47MGiPsqZp3W8tVeMJff3cLOCCJn9Bb71YO53Gygdfw/ucu1uGg13t51GMkQVQs1hyNrzaJorizkMMlT5J8WKS4Q1OromcXr1c/FdN+nCLuAU76BjUB/oGLG5olv3QW0MpX1AiEAymYzxGus3XoX/3nYVCdgaxOJobx8BdMu3sHUArcXXr/h/cF1KxytZ+xYUa1VRfO1xcQNuv8pQKLDjuz0wwlCF3Wg6ak2tOvsSDmk3L08VTeb+/OtH6xOftvCfEH96rDB3PLE1IpzU0evM3oAayifHA/VKLmrTOmKHbVPH+QFZJ71OT8AkTBj2WETX0uoGoHEuFmK1uXOIwwSelt8Nrcuokpsd8YZF9Db9WVCt+Wr7zg8Fidc3ky0G0HqmC2o9ab30qi0iqpzSXTd7oHEr1+waWs3t6TAX7IYB1c4ziAXZ3DLd1AIntkXRN/9eRvwMDLyRfEKSppD86Geq+E041MSxq21MXc/oZweQ17fuC6MMUuxo8bwvYcruMXvwf5d7IKKXwUR9Pqin6V0g0S0hqpKCGqJw7Y0Mj8yDK/zhlmQVDwA+4Mhyd6Tpxtm8HtGFaV7K7Sxn85+5V18UqxSAF+dS34lrJToGPoQwnxzKvCWUEOz99ZFrTJtJQYw8Nisv4LgDtQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
