travis:
  secure:
    BINSTAR_TOKEN: j40zK9V9dCPrQMKPYsrTtgrOXC1cH5LZdk/Tjnu6EVsql2EXI/boURPjewQPyus57oeAyYUth4prynAC7ReV3LlzNQnC6tPTBt3Q8ybMKS57Xiub+gIdHxh4xx9zxv8W7k4ITuNetcPaCVZHI0spRJqp+kswd8iSJCmGQfs63Ht0XfLLYxPWRW9ZctYOmflD5bR7ZsTA4PiC6YugatLLHtwTGHU6gB7SY2fz/5Tzbxrx5n3DImpR8pGfA0y188IcxG34e6U1dGOMR16qg4TA/H1G9Hl6iJjww1D3LjCa8hr+GjZb+pqGYckQkSzwtDYtkyUS5hB/tv9/b/hq5shmTSy40mAnRgntetaVcoajTzd4Gw9tIliHQCFcQnbFlK1AalZmOvuWSyMG0iSLjeCIexsL6b6pr3CFgQ4z7exs3j14Y1M8ZP+kWxr9XzE1jg9Qrilwb+T7AznDDkzRXXZHHwLYYqE+xXMY4QEQnL6D/Iy216J12DL11gIhEn8LwAj4GFHyhEDi8w7xXg9ETQM/enZLJZamkrJCxJ25GTKu0xQPkKii3rbTHgkN99SkN8Tr9+5ts1F6BVTS1pB3F5lIHUchmwqOQSrs4DJTjO/5wG7Twux4QMlIubiIdkKElUAW7F1KqXYO/i6qjVZBKLEB7RQnDbU58nL4JBmMBm/6Pno=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
